DELETE http://localhost:4000/api/tickets/0b2fd891-a728-4b6c-a83e-60081f0fb702 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2IzOGUzYzFmMWU5NjYzNWUyOTgzYjMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4MzE3ODAsImV4cCI6MTczOTgzNTM4MH0.I98ZZ0T9YTAFkdPkAGWwM12jR11TJ5ttUTcCLNrpdjA