//Crear ticket con usuario autenticado
POST http://localhost:4000/api/tickets/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2IzOGUzYzFmMWU5NjYzNWUyOTgzYjMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4MzgwMTQsImV4cCI6MTczOTg0MTYxNH0.vfh-he2z6FJJe0dxYAY2y0SEWVjUMM0A5RzJ3ZnjQuQ

{
    "title": "Ticket #15",
    "description": "Example description."
}